#!/bin/sh
# -*- tab-width: 4 -*- ;; Emacs
# vi: set noexpandtab  :: Vi/ViM
############################################################ IDENT(1)
#
# $Title: Script for re-populating the package staging files from RPM $
# $Copyright: 2019-2020 Devin Teske. All rights reserved. $
# $FrauBSD: pkgcenter-R/redhat/Mk/rpmrestage 2020-07-16 18:21:22 -0700 freebsdfrau $
#
############################################################ INFORMATION
#
# Usage: rpmrestage
#
############################################################ GLOBALS

#
# Global exit status
#
SUCCESS=0
FAILURE=1

#
# OS Glue
#
: ${UNAME_s:=$( uname -s )}
: ${UNAME_p:=$( uname -p )}

#
# Utility pathnames
#
: ${AWK:=awk}
: ${CPIO:=cpio}
: ${ENV:=env}
: ${LS:=ls}
: ${MKDIR:=mkdir}
: ${RPM2CPIO:=rpm2cpio}
: ${YUM:=yum}
: ${YUMDOWNLOADER:=yumdownloader}

#
# Miscellaneous
#
FILE=
NAME=
RPMNAME=
_RPMNAME=

############################################################ MAIN

set -e # errexit

#
# Download the RPM using yumdownloader (from yum-utils)
#
RPMNAME=$( $PKGCENTER/redhat/Mk/rpmname "$SPECFILE" )
if ! [ -e "$RPMNAME.$UNAME_p.rpm" ]; then
if ! $ENV -i $YUMDOWNLOADER -y "$RPMNAME"; then
	NAME=$( $AWK 'sub(/^[Nn][Aa][Mm][Ee]:[[:space:]]*/, "")' "$SPECFILE" )
	_RPMNAME=$( $ENV -i $YUM info -q -C "$NAME" | $AWK '
		$1 == "Name" { name = $NF }
		$1 == "Version" { vers = $NF }
		$1 == "Release" { rel = $NF }
		END { if (name != "") printf "%s-%s-%s\n", name, vers, rel }
	' )
	if [ ! "$_RPMNAME" ]; then
		echo "$NAME unknown"
		echo "#"
		echo "# Please find $RPMNAME.$UNAME_p.rpm"
		echo "#"
		exit $FAILURE
	fi
	RPMNAME="$_RPMNAME"
	$ENV -i $YUMDOWNLOADER -y "$RPMNAME"
fi
fi # -e $RPMNAME.$UNAME_p.rpm
for FILE in $( $LS -tr $RPMNAME*.rpm ); do
	break
done

#
# Unpack the RPM
#
no_absolute_filenames=
[ "$UNAME_s" = Linux ] && no_absolute_filenames=--no-absolute-filenames
set -x
$MKDIR -p stage
$RPM2CPIO "$FILE" | ( cd stage &&
	$CPIO -idmu $no_absolute_filenames --no-preserve-owner )

################################################################################
# END
################################################################################
