# -*- tab-width: 4 -*- ;; Emacs
# vi: set noexpandtab  :: Vi/ViM
############################################################ IDENT(1)
#
# $Title: Makefile for installing scripts $
# $Copyright: 2019 Devin Teske. All rights reserved. $
# $FrauBSD: pkgcenter-R/depend/afput/Makefile 2019-07-12 16:42:10 -0700 freebsdfrau $
#
############################################################ CONFIGURATION

DESTDIR=	~/bin/
PROGS=		afput

############################################################ TARGETS

install:
	mkdir -p $(DESTDIR)
	cp -av $(PROGS) $(DESTDIR)

################################################################################
# END
################################################################################
