#!/bin/sh
# -*- tab-width: 4 -*- ;; Emacs
# vi: set noexpandtab  :: Vi/ViM
############################################################ IDENT(1)
#
# $Title: Script for importing a directory to git $
# $Copyright: 1999-2020 Devin Teske. All rights reserved. $
# $FrauBSD: pkgcenter-R/depend/import 2020-07-16 18:21:22 -0700 freebsdfrau $
#
############################################################ INFORMATION
#
# Usage: import PATH ...
#
############################################################ GLOBALS

#
# Global exit status
#
SUCCESS=0
FAILURE=1

#
# Command-line options
#
MESSAGE=	# -m msg

#
# Utility pathnames
#
: ${GIT:=git}
: ${TEE:=tee}

############################################################ MAIN

#
# Process command-line options
#
while getopts m: flag; do
	case "$flag" in
	m) MESSAGE="$OPTARG" ;;
	*) echo "Usage: ${0##*/} [-m msg] PATH ..." >&2
	   exit $FAILURE
	esac
done
shift $(( $OPTIND - 1 ))

set -e
added=$( $GIT add -v "$@" | $TEE /dev/stderr ) 2>&1
if [ "$added" ]; then
	$GIT commit ${MESSAGE:+-m "$MESSAGE"}
fi

exit $SUCCESS

################################################################################
# END
################################################################################
