#!/bin/sh
############################################################ IDENT(1)
#
# $Title: Script to list library differences between two R distributions $
# $Copyright: 2019 Devin Teske. All rights reserved. $
# $FrauBSD: pkgcenter-R/depend/vcr/libexec/cmp 2019-07-12 14:05:39 -0700 freebsdfrau $
#
############################################################ ENVIRONMENT

#
# Inherited from vcr
#
: ${VCR_PROGRAM:=vcr}

############################################################ GLOBALS

#
# Program basename
#
case "$( uname -s )" in
Linux)
	pgm=$( readlink -f "$0" )
	pgm="${pgm##*/}"
	;;
*)
	pgm="${0##*/}"
esac

#
# Global exit status
#
SUCCESS=0
FAILURE=1

#
# mktemp
#
MKTEMP_TEMPLATE="$VCR_PROGRAM.$pgm.XXXXXXXX"

############################################################ I18N

case "${LANG:-$LC_ALL}" in
de|de_DE|de_DE.*) # German
msg_unable_to_create_temporary_directory="Temporäres verzeichnis kann nicht erstellt werden"
msg_usage="Verwendungszweck"
;;
he|he_IL|he_IL.*) # Hebrew
msg_unable_to_create_temporary_directory="לא ניתן ליצור ספריה זמנית"
msg_usage="שימוש"
;;
pl|pl_PL|pl_PL.*) # Polish
msg_unable_to_create_temporary_directory="Nie można utworzyć katalogu tymczasowego"
msg_usage="Stosowanie"
;;
ru_RU.UTF8) # Russian (Cyrillic)
msg_unable_to_create_temporary_directory="Невозможно создать временный каталог"
msg_usage="Использование"
;;
ru|ru_RU|ru_RU.*) # Russian (Latin)
msg_unable_to_create_temporary_directory="Nevozmozhno sozdat' vremennyy katalog"
msg_usage="Ispol'zovaniye"
;;
zh_CN.UTF8) # Chinese (Simplified)
msg_unable_to_create_temporary_directory="无法创建临时目录"
msg_usage="用法"
;;
zh|zh_CN|zh_CN.*) # Chinese (Latin)
msg_unable_to_create_temporary_directory="Wúfǎ chuàngjiàn línshí mùlù"
msg_usage="Yòngfǎ"
;;
*) # English
msg_unable_to_create_temporary_directory="Unable to create temporary directory"
msg_usage="Usage"
esac

############################################################ FUNCTIONS

have()
{
	type "$@" > /dev/null 2>&1
}

die()
{
	local fmt="$1"
	if [ "$fmt" ]; then
		shift 1 # fmt
		printf "%s: %s: $fmt\n" "$VCR_PROGRAM" "$pgm" "$@"
	fi
	exit $FAILURE
}

usage()
{
	local optfmt="\t%-9s %s\n"
	exec >&2
	printf "$msg_usage: %s %s dirA dirB\n" "$VCR_PROGRAM" "$pgm"
	die
}

############################################################ MAIN

#
# Command-line options
#
while getopts h flag; do
	case "$flag" in
	*) usage # NOTREACHED
	esac
done
shift $(( $OPTIND - 1 ))

#
# Check command-line arguments
#
if [ $# -ne 2 ]; then
	usage
	# NOTREACHED
fi

#
# Get library versions
#
tmpdir=$( mktemp -d "$MKTEMP_TEMPLATE" ) ||
	die "$msg_unable_to_create_temporary_directory"
trap 'rm -Rf "$tmpdir"' EXIT
dirA="${1%/}"
dirB="${2%/}"
vcr list -s "$dirA" > "$tmpdir/A.txt" || die
vcr list -s "$dirB" > "$tmpdir/B.txt" || die

#
# Display differences
#
if [ -t 1 ] && have vimcat; then # stdout is a tty
	diff -pu "$tmpdir/A.txt" "$tmpdir/B.txt" | vimcat |
		awk 'NR==1{next}NR==2&&!/-/{next}1'
else
	diff -pu "$tmpdir/A.txt" "$tmpdir/B.txt"
fi

exit $SUCCESS

################################################################################
# END
################################################################################
