#!/bin/sh
############################################################ IDENT(1)
#
# $Title: Script to open library archive $
# $Copyright: 2019-2020 Devin Teske. All rights reserved. $
# $FrauBSD: pkgcenter-R/depend/vcr/libexec/untar 2020-07-16 16:40:51 -0700 freebsdfrau $
#
############################################################ ENVIRONMENT

#
# Inherited from vcr
#
: ${VCR_PROGRAM:=vcr}

############################################################ GLOBALS

#
# Program basename
#
case "$( uname -s )" in
Linux)
	pgm=$( readlink -f "$0" )
	pgm="${pgm##*/}"
	;;
*)
	pgm="${0##*/}"
esac

#
# Global exit status
#
SUCCESS=0
FAILURE=1

#
# Command-line options
#
DEST=		# -d dir

############################################################ I18N

case "${LANG:-$LC_ALL}" in
de|de_DE|de_DE.*) # German
msg_destination_directory="Zielverzeichnis."
msg_options="Optionen"
msg_print_help_message="Hilfemeldung an stderr ausgeben und beenden."
msg_usage="Verwendungszweck"
;;
he|he_IL|he_IL.*) # Hebrew
msg_destination_directory="ספריית יעד."
msg_options="אפשרויות"
msg_print_help_message="הדפס את הודעת העזרה ל stdr ולצאת."
msg_usage="שימוש"
;;
ja_JP.UTF8) # Japanese (Kanji)
msg_destination_directory="宛先ディレクトリ。"
msg_options="オプション"
msg_print_help_message="ヘルプメッセージをstderrに出力して終了します。"
msg_usage="使用法"
;;
ja|ja_JP|ja_JP.*) # Japanese (Latin)
msg_destination_directory="Atesaki direkutori."
msg_options="Opushon"
msg_print_help_message="Herupumessēji o stderr ni shutsuryoku shite shūryō shimasu."
msg_usage="Shiyō-hō"
;;
pl|pl_PL|pl_PL.*) # Polish
msg_destination_directory="Katalog docelowy."
msg_options="Opcje"
msg_print_help_message="Wydrukuj komunikat pomocy na stderr i wyjdź."
msg_usage="Stosowanie"
;;
ru_RU.UTF8) # Russian (Cyrillic)
msg_destination_directory="Целевой каталог."
msg_options="Опции"
msg_print_help_message="Распечатать справочное сообщение в stderr и выйти."
msg_usage="Использование"
;;
ru|ru_RU|ru_RU.*) # Russian (Latin)
msg_destination_directory="Tselevoy katalog."
msg_options="Optsii"
msg_print_help_message="Raspechatat' spravochnoye soobshcheniye v stderr i vyyti."
msg_usage="Ispol'zovaniye"
;;
zh_CN.UTF8) # Chinese (Simplified)
msg_destination_directory="目标目录。"
msg_options="选项"
msg_print_help_message="将帮助消息打印到stderr并退出。"
msg_usage="用法"
;;
zh|zh_CN|zh_CN.*) # Chinese (Latin)
msg_destination_directory="Mùbiāo mùlù."
msg_options="Xuǎnxiàng"
msg_print_help_message="Jiāng bāngzhù xiāoxī dǎyìn dào stderr bìng tuìchū."
msg_usage="Yòngfǎ"
;;
*) # English
msg_destination_directory="Destination directory."
msg_options="Options"
msg_print_help_message="Print help message to stderr and exit."
msg_usage="Usage"
esac

############################################################ FUNCTIONS

die()
{
	local fmt="$1"
	if [ "$fmt" ]; then
		shift 1 # fmt
		printf "%s: %s: $fmt\n" "$VCR_PROGRAM" "$pgm" "$@"
	fi
	exit $FAILURE
}

usage()
{
	local optfmt="\t%-9s %s\n"
	exec >&2
	printf "$msg_usage: %s %s [-h] [-d dir] file\n" "$VCR_PROGRAM" "$pgm"
	printf "$msg_options:\n"
	printf "$optfmt" "-d dir" "$msg_destination_directory"
	printf "$optfmt" "-h" "$msg_print_help_message"
	die
}

############################################################ MAIN

#
# Command-line options
#
while getopts d:h flag; do
	case "$flag" in
	d) DEST="$OPTARG" ;;
	*) usage # NOTREACHED
	esac
done
shift $(( $OPTIND - 1 ))

#
# Check command-line arguments
#
if [ $# -lt 1 ]; then
	usage
	# NOTREACHED
fi

#
# Unpack archives
#
set -e # errexit
for path in "$@"; do
	tar zxf "$path" ${DEST:+-C "$DEST"}
done

exit $SUCCESS

################################################################################
# END
################################################################################
